### ISSUE TITLE
Skeleton considers only unique simplices

### ISSUE THREAD

**Issue by shakisparki** [krcools/CompScienceMeshes.jl#18]
Consider a geometry with multiple faces/cells having the same tuple of indices in the vertex buffer are to be kept as separate faces.
Finding the skeleton of such geometry using `skeleton(mesh,dim)` will consider all such faces as one, effectively reducing the number of expected cells. In the case of `skeleton(mesh,dim=1)` for distinct overlapping sheets welded together along the boundary, this can force a junction edge where a regular internal edge is expected.

**Comment by krcools** [comment]
Thin mesh support is now in place and based on the duplication of all vertices that are not on the boundary of the mesh. Entities on the front and back are now logically distinguishable.
